server:
  port: 5001

spring:
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git: #远程仓库git的地址
          uri: https://github.com/18286132146/microservice-cloud-config.git
